# Generated by Django 4.1.3 on 2022-12-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('idEstacionamiento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id estacionamiendo')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('numero', models.IntegerField(verbose_name='Numero de estacionamiendos disponibles')),
                ('titular', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='titular')),
            ],
        ),
    ]
